fixed the code sanning alerts

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -37,13 +37,13 @@ jobs:
         # Learn more:
         # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
 
+    # Specify the container in which actions will run
+    container:
+      image: gradle:latest
+
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
-      with:
-        # We must fetch at least the immediate parents so that if this is
-        # a pull request then we can checkout the head.
-        fetch-depth: 2
 
     # If this run was triggered by a pull request event, then checkout
     # the head of the pull request instead of the merge commit.
@@ -63,21 +63,34 @@ jobs:
 
     # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
     # If this step fails, then you should remove it and run the build manually (see below)
-    # - name: Autobuild
-    #   uses: github/codeql-action/autobuild@v1
+    #- name: Autobuild
+    #  uses: github/codeql-action/autobuild@v1
 
-    # Command-line programs to run using the OS shell.
-    # https://git.io/JvXDl
+    # ℹ️ Command-line programs to run using the OS shell.
+    # 📚 https://git.io/JvXDl
 
-    # If the Autobuild fails above, remove it and uncomment the following three lines
-    # and modify them (or add more) to build your code if your project
-    # uses a compiled language
+    # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
+    #    and modify them (or add more) to build your code if your project
+    #    uses a compiled language
+
     - run: |
        chmod +x gradlew
        ./gradlew build
-    #- run: |
     #   make bootstrap
     #   make release
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v1
+      with:
+        output: ./scan-results
+
+    - run: |
+        apt-get update && apt-get install -y jq
+        ls -al ./scan-results
+        set +e
+        cat ./scan-results/java-builtin.sarif | jq -e '.runs[0].results | select(length > 0)'
+        if [ "$?" -eq 0 ]
+        then
+        echo "Vulnerabilities detected. Failing the action"
+        exit 1
+        fi
